name:                pips
version:             0.1.0.0
github:              "TengenJulian/Haskell-Download-Manager"
license:             BSD3
author:              "David Veenstra"
maintainer:          "davidjulianveenstra@gmail.com"
copyright:           "2018 David Veenstra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-download-manager#readme>

dependencies:
- base >=4.8 && <= 4.11
- Yampa
- parsec
- microlens
- microlens-th
- vty
- deepseq
- brick
- vector
- text
- containers
- optparse-applicative
- directory

library:
  source-dirs: src

executables:
  pips:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -fwarn-unused-do-bind
    dependencies:
    - pips
